services:
  # 后端 API 服务
  - type: web
    name: trade-backend-api
    runtime: node
    repo: https://github.com/your-username/your-repo.git
    branch: main
    rootDir: ./backend
    buildCommand: npm install && npm run build
    startCommand: npm start
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: DATABASE_URL
        fromDatabase:
          name: trade-postgres
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET  
        generateValue: true
      # 其他环境变量需要手动添加
    
  # 前端静态网站
  - type: web
    name: trade-frontend-web
    runtime: static
    repo: https://github.com/your-username/your-repo.git
    branch: main
    rootDir: ./frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    plan: free
    envVars:
      - key: REACT_APP_API_URL
        value: https://trade-backend-api.onrender.com

# 数据库服务
databases:
  - name: trade-postgres
    databaseName: trade_platform
    user: trade_user
    plan: free
    
# 静态资源服务（可选）
  - type: web
    name: trade-static-assets
    runtime: static
    repo: https://github.com/your-username/your-repo.git
    branch: main
    staticPublishPath: ./uploads
    plan: free